# Generated by Django 4.2.9 on 2024-01-29 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="storage_created",
        ),
        migrations.AddField(
            model_name="organization",
            name="bucket_name",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 14, 7, 43, 280041, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 14, 7, 43, 279300, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
