# Generated by Django 4.2.9 on 2024-02-20 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsofserviceversion",
            name="file_size",
            field=models.IntegerField(default=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 8, 16, 45, 500075, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 8, 16, 45, 499291, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
