# Generated by Django 4.2.9 on 2024-01-29 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_organization_storage_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 14, 25, 14, 171349, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 14, 25, 14, 170761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
