# Generated by Django 4.2.9 on 2024-02-21 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_organization_logo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo_url",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 10, 3, 52, 960928, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 21, 10, 3, 52, 960206, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
