# Generated by Django 4.2.9 on 2024-01-24 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_termsofservice_versions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 24, 11, 11, 3, 122915, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 24, 11, 11, 3, 122355, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
