# Generated by Django 4.2.9 on 2024-02-22 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_organization_logo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsofservice",
            name="description",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 22, 8, 15, 6, 158, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 22, 8, 15, 5, 999299, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
