# Generated by Django 4.2.9 on 2024-01-31 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_termsofservice_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 31, 11, 12, 59, 253824, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="versions",
            field=models.ManyToManyField(blank=True, to="api.termsofserviceversion"),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 31, 11, 12, 59, 253092, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
