# Generated by Django 4.2.9 on 2024-02-23 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_termsofservice_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termsofservice",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="termsofserviceversion",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 23, 10, 23, 21, 798952, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 23, 10, 23, 21, 798083, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
