# Generated by Django 4.2.9 on 2024-03-06 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_termsofservice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IAMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 6, 12, 41, 57, 292779, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 6, 12, 41, 57, 291908, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
