# Generated by Django 4.2.9 on 2024-01-31 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_termsofservice_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 31, 12, 42, 53, 55396, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 31, 12, 42, 53, 54669, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="version_number",
            field=models.IntegerField(),
        ),
    ]
