# Generated by Django 4.2.9 on 2024-03-09 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_iamtoken_alter_termsofservice_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsofservice",
            name="slug",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 9, 8, 47, 10, 966512, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 9, 8, 47, 10, 965756, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
