# Generated by Django 4.2.9 on 2025-02-07 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_termsofservice_slug_alter_termsofservice_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termsofserviceversion",
            options={"ordering": ["-version_number"]},
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 7, 8, 29, 18, 587501, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termsofserviceversion",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 7, 8, 29, 18, 586695, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
